version: '3.3'

services:
  nginx-gateway:
    image: nginx:alpine
    volumes:
      - ./config/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/etc/nginx/conf.d/local.conf:/etc/nginx/conf.d/local.conf
      - ./runtime/logs/nginx:/var/log/nginx
    ports:
      - 80:80
    networks:
      social-backend:

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - database.env
    ports:
      - 3306:3306
volumes:
  db_data: {}
networks:
  social-backend:
